'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class employee
    Public Property id As Integer
    Public Property first_name As String
    Public Property last_name As String
    Public Property phone As String
    Public Property addres As String
    Public Property id_type_employee As Nullable(Of Integer)
    Public Property working_day As String
    Public Property state As String
    Public Property created_at As Nullable(Of Date)
    Public Property updated_at As Nullable(Of Date)

    Public Overridable Property groups As ICollection(Of group) = New HashSet(Of group)
    Public Overridable Property inscripcions As ICollection(Of inscripcion) = New HashSet(Of inscripcion)
    Public Overridable Property type_employees As type_employees
    Public Overridable Property users As ICollection(Of user) = New HashSet(Of user)

End Class
