'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class extra_payments
    Public Property id As Integer
    Public Property id_student As Nullable(Of Integer)
    Public Property id_payment As Nullable(Of Integer)
    Public Property id_type_payment As Nullable(Of Integer)
    Public Property amount As Nullable(Of Integer)
    Public Property balance As Nullable(Of Integer)
    Public Property state As String
    Public Property created_at As Nullable(Of Date)
    Public Property updated_at As Nullable(Of Date)

    Public Overridable Property payment As payment
    Public Overridable Property student As student
    Public Overridable Property payment_types As payment_types

End Class
