'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class group
    Public Property id As Integer
    Public Property id_program As Nullable(Of Integer)
    Public Property id_laboratorie As Nullable(Of Integer)
    Public Property id_employee As Nullable(Of Integer)
    Public Property time_practice As Nullable(Of Integer)
    Public Property day As String
    Public Property schedule As String
    Public Property state As String
    Public Property created_at As Nullable(Of Date)
    Public Property updated_at As Nullable(Of Date)

    Public Overridable Property detailgroups As ICollection(Of detailgroup) = New HashSet(Of detailgroup)
    Public Overridable Property employee As employee
    Public Overridable Property inscripcions As ICollection(Of inscripcion) = New HashSet(Of inscripcion)
    Public Overridable Property laboratory As laboratory
    Public Overridable Property program As program
    Public Overridable Property schedules_practice As schedules_practice

End Class
