'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class AcademiaEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=AcademiaEntities")
    End Sub
    Public Sub New(ByVal conexion As String)
        MyBase.New(conexion)
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property detailgroups() As DbSet(Of detailgroup)
    Public Property employees() As DbSet(Of employee)
    Public Property extra_payments() As DbSet(Of extra_payments)
    Public Property groups() As DbSet(Of group)
    Public Property inscripcions() As DbSet(Of inscripcion)
    Public Property laboratories() As DbSet(Of laboratory)
    Public Property passwordresets() As DbSet(Of passwordreset)
    Public Property payment_types() As DbSet(Of payment_types)
    Public Property payments() As DbSet(Of payment)
    Public Property programs() As DbSet(Of program)
    Public Property schedules_practice() As DbSet(Of schedules_practice)
    Public Property shares() As DbSet(Of share)
    Public Property students() As DbSet(Of student)
    Public Property sysdiagrams() As DbSet(Of sysdiagram)
    Public Property typeemployees() As DbSet(Of typeemployee)
    Public Property users() As DbSet(Of user)

End Class
