'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class passwordreset
    Public Property id As Integer
    Public Property email As String
    Public Property token As String
    Public Property created_at As Nullable(Of Date)
    Public Property updated_at As Nullable(Of Date)

End Class
