'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class payment
    Public Property id As Integer
    Public Property no_document As String
    Public Property description As String
    Public Property amount As Nullable(Of Integer)
    Public Property state As String
    Public Property id_type As Nullable(Of Integer)
    Public Property id_user As Nullable(Of Integer)
    Public Property id_student As Nullable(Of Integer)
    Public Property created_at As Nullable(Of Date)
    Public Property updated_at As Nullable(Of Date)

    Public Overridable Property extra_payments As ICollection(Of extra_payments) = New HashSet(Of extra_payments)
    Public Overridable Property inscripcions As ICollection(Of inscripcion) = New HashSet(Of inscripcion)
    Public Overridable Property payment_types As payment_types
    Public Overridable Property shares As ICollection(Of share) = New HashSet(Of share)
    Public Overridable Property user As user
    Public Overridable Property student As student
    Public Overridable Property detail_Extra_Payments As ICollection(Of detail_Extra_Payments) = New HashSet(Of detail_Extra_Payments)

End Class
