'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class share
    Public Property id As Integer
    Public Property id_inscripcion As Nullable(Of Integer)
    Public Property id_payment As Nullable(Of Integer)
    Public Property date_share As Nullable(Of Date)
    Public Property amount As Nullable(Of Integer)
    Public Property balance As Nullable(Of Integer)
    Public Property mora As Nullable(Of Integer)
    Public Property created_at As Nullable(Of Date)
    Public Property updated_at As Nullable(Of Date)

    Public Overridable Property inscripcion As inscripcion
    Public Overridable Property payment As payment

End Class
