'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class student
    Public Property id As Integer
    Public Property first_name As String
    Public Property last_name As String
    Public Property phone As String
    Public Property addres As String
    Public Property date_of_birth As Nullable(Of Date)
    Public Property in_charge As String
    Public Property state As String
    Public Property created_at As Nullable(Of Date)
    Public Property updated_at As Nullable(Of Date)

    Public Overridable Property detailgroups As ICollection(Of detailgroup) = New HashSet(Of detailgroup)
    Public Overridable Property extra_payments As ICollection(Of extra_payments) = New HashSet(Of extra_payments)
    Public Overridable Property payments As ICollection(Of payment) = New HashSet(Of payment)
    Public Overridable Property tics As ICollection(Of tic) = New HashSet(Of tic)

End Class
