'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class user
    Public Property id As Integer
    Public Property username As String
    Public Property password As String
    Public Property remember_token As String
    Public Property type As String
    Public Property id_employee As Nullable(Of Integer)
    Public Property state As String
    Public Property created_at As Nullable(Of Date)
    Public Property updated_at As Nullable(Of Date)

    Public Overridable Property employee As employee
    Public Overridable Property inscripcions As ICollection(Of inscripcion) = New HashSet(Of inscripcion)
    Public Overridable Property payments As ICollection(Of payment) = New HashSet(Of payment)

End Class
